version: "3"

networks:
  tekwerk:
    external: false

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    networks:
      - tekwerk
    volumes:
      - /tekwerk/volumes/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "11000:3000"
      - "22"
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - tekwerk
    volumes:
      - /tekwerk/volumes/postgres:/var/lib/postgresql/data

  jenkins:
    image: tekwerk/jenkins:latest
    restart: always
    ports:
      - "11001:8080"
      - "50000:50000"
    volumes:
      - /tekwerk/volumes/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
